### ISSUE TITLE
Wholesale prices

### ISSUE THREAD

**Issue by negati-ve** [vivepandit24/visario#10]
Steps to reproduce issue
- Logging in as wholesaler
![screen shot 2017-03-20 at 11 20 30 pm](https://cloud.githubusercontent.com/assets/13253073/24113799/ed3baea0-0dc3-11e7-8498-d9f9393b014d.png)

- Then visiting https://visi.000webhostapp.com/product/soft-copper-pipe-copper-pancake-coil-6-mm-o-d/ shows 
![screen shot 2017-03-20 at 11 22 36 pm](https://cloud.githubusercontent.com/assets/13253073/24113857/25cd0f2a-0dc4-11e7-997b-36a91a092528.png)

**Comment by negati-ve** [comment]
this is solved by changing the user role from "wholesale-customer" to "wholeseller"

**Comment by negati-ve** [comment]
after changing role, 
![screen shot 2017-03-20 at 11 27 26 pm](https://cloud.githubusercontent.com/assets/13253073/24114046/d89f10b2-0dc4-11e7-8031-2e9fff12e931.png)

**Comment by ghost** [comment]
there should be only one price shown...no strikes. Also check the price range. It should be according to wholesale prices. Currently price range not showing up.

**Comment by negati-ve** [comment]
This requires Custom coding. 
- Striked original price can be removed by editing line 324 of wp-content/plugins/woocommerce/includes/class-wc-product-variation.php

Replace
`$price = apply_filters( 'woocommerce_variation_sale_price_html', '<del>' . wc_price( $display_regular_price ) . '</del> <ins>' . wc_price( $display_sale_price ) . '</ins>' . $this->get_price_suffix(), $this );
`
with
`$price = apply_filters( 'woocommerce_variation_sale_price_html', '<ins>' . wc_price( $display_sale_price ) . '</ins>' . $this->get_price_suffix(), $this );
`

Doing this will conflict with any future woo commerce updates. 
Please confirm if you'd like us to implement this.

**Comment by negati-ve** [comment]
![screen shot 2017-03-21 at 5 57 40 pm](https://cloud.githubusercontent.com/assets/13253073/24147384/f1407ba6-0e5f-11e7-92c7-84268270973f.png)

**Comment by ghost** [comment]
Wholesale price range not showing

**Comment by negati-ve** [comment]
custom implemented on top woocommerce market plugin.  
- no more woocommerce core edits. 
- wholesale price range showing now
- no striked out text

custom theme css required as follows:
```
.price{
font-size:24
} 
```
to make the fonts match the current theme.

you can now download the whole plugin folder and reuse it in production website. 

Please confirm on this with a comment here upon which this issue will be closed

**Comment by ghost** [comment]
Home page
Featured product - Wholesale price range missing. 

Shop page - Wholesale price range missing.

Regular price range visible

**Comment by negati-ve** [comment]
where is the regular range visible?

**Comment by ghost** [comment]
Wholesale Shop

![shop ws](https://cloud.githubusercontent.com/assets/26554401/24163935/09e041c8-0e92-11e7-994f-9e4afa78a1e9.PNG)

Wholesale Home

![home ws](https://cloud.githubusercontent.com/assets/26554401/24163934/09dc4ee2-0e92-11e7-9a2d-89419aad1169.PNG)

**Comment by ghost** [comment]
Retail Shop

![shop retail](https://cloud.githubusercontent.com/assets/26554401/24163972/373c5a62-0e92-11e7-8369-201d95a579c6.PNG)

Retail Home

![home rettail](https://cloud.githubusercontent.com/assets/26554401/24163973/37400c5c-0e92-11e7-8b51-956783745117.PNG)

**Comment by negati-ve** [comment]
you are logged in as 'a' which is not a wholesale user. 
Do you want the range to be not visible there for normal user?

**Comment by ghost** [comment]
Logged as ws
Wholesale shop works as discussed
Whole home  - featured product wholesale price range not showing

Logged as a
Both image is just for ref on how price range shows
No change required for normal user

**Comment by negati-ve** [comment]
Assigning this to @vivepandit24. 
Please make sure that the wholesale price range appears on the featured  products. 

If you need any help, please feel comfortable to post here and I'll try and help out.

**Comment by vivepandit24** [comment]
Core files of the vg woocommerce needs to be altered.

C:\xampp\htdocs\wp\wp-content\plugins\vg-woocarousel\themes\default\index.php:

292: 					$vgwc_price 	= $product->get_price_html();

As we can see here a woo commerce core function **get_price_html()**  which is true for normal user but needs to change for a wholesale customer.

vgwc_price holds the value for vgwc_product_price in

possible solution (can only confirm after implementing)-

new variable similar to vgwc-price which hold the custom meta   get_post_meta($post_id, $key, $single = false) asign it to vgwc_product_price1.

switch between vgwc_product_price && vgwc_product_price1 based on role of user.

````
function has_role_WPA111772($role = '',$user_id = null){
    if ( is_numeric( $user_id ) )
        $user = get_user_by( 'id',$user_id );
    else
        $user = wp_get_current_user();

    if ( empty( $user ) )
        return false;

    return in_array( $role, (array) $user->roles );
`
```}``

to identify user role.

plugin cannot be updated in future if so an offline backup has to be kept and needs o be uploaded over ftp everytime there is an update.

**Comment by vivepandit24** [comment]
```
add_filter('woocommerce_get_price', 'custom_price_WPA111772', 10, `2);`
/**
 * custom_price_WPA111772 
 *
 * filter the price based on category and user role
 * @param  $price   
 * @param  $product 
 * @return 
 */

function custom_price_WPA111772($price, $product) {
    if (!is_user_logged_in()) return $price;

     {
        //check if the user has a role of dealer using a helper function, see bellow
        if (has_role_WPA111772('wholeseller')){
            global $post, $blog_id;
    $price = get_post_meta($post->ID, 'wm_price');
    $post_id = $post->ID;
        }
    }
    return $price;
}

/**
 * has_role_WPA111772 
 *
 * function to check if a user has a specific role
 * 
 * @param  string  $role    role to check against 
 * @param  int  $user_id    user id
 * @return boolean
 */
function has_role_WPA111772($role = '',$user_id = null){
    if ( is_numeric( $user_id ) )
        $user = get_user_by( 'id',$user_id );
    else
        $user = wp_get_current_user();

    if ( empty( $user ) )
        return false;

    return in_array( $role, (array) $user->roles );
}
```

**Comment by vivepandit24** [comment]
@negati-ve  This is a possible solution which will not interfere with plugin updates. 
let me know what you think about it....

@nishiyt  please share the excel sheet with the normal and wholesale prices . Need to check if the solution works properly.

**Comment by negati-ve** [comment]
First of all, Sorry about the delay.. Was caught up with some personal work yesterday.

Thanks @vivepandit24 for the code above. 
unfortunately, we can't use that solution cause "wm_price" is not a variable that is available on the home page since *wholesale market plugin* hooks only into the shop and single product page . 

I've worked up a custom solution to this by rewriting wholesale market plugin (major edit) and a bit of VG carousel plugin (minor edit).
There is no easy way out if you need control over things. and once the production site is built I'd recommend not upgrading wholesale market and carousel plugin unless **necessary**

Please check and verify this and create a copy of the plugin folders. We shall rename the plugins and turn them into our own versions (yup. that's totally legal as it falls under GPL license)
