### ISSUE TITLE
Apply for wholesaler account [form]

### ISSUE THREAD

**Issue by negati-ve** [vivepandit24/visario#11]
-user can upgrade account to whole saler by following menu link to 
https://visi.000webhostapp.com/membership-account/membership-levels/

- one paid, users account will be upgraded to pmpro-wholsaler_final and prices set for pmpro-wholsaler_final will be shown 

please confirm if this is desired flow

**Comment by negati-ve** [comment]
registration remains simple and unaffected if we follow this path. please reply with your input

**Comment by vivepandit24** [comment]
Perfect for Registration......will it support dual shipping ??

**Comment by negati-ve** [comment]
What do you mean by dual shipping ? It'll support everything a normal wholesaler account would support

**Comment by ghost** [comment]
Seems fine as per option shown.
But can confirm on seeing the entire flow from free registration part to upgrade.

**Comment by negati-ve** [comment]
@vivepandit24 informed me that you need the wholesaler's additional details to be captured. 
Please posts the final fields req for the registration here..

**Comment by ghost** [comment]
- Name*
- Email (used for login) (verification)*
- Password*
- Mobile number (verification)* - Country code box (+ sign on left) and another box with 10 digit validation

**Upgrade**

- Business/Company name (as mentioned on business license)* - Textbox
- Business/Company type - Radio button*
	Sole Proprietorship
	Partnership
	Private Limited Company
	Limited Liability Partnership (LLP)
- Reason for purchase* - Multi Select
	Personal Use
	Re-sell
- Business/Company Pan number - 10-digit alphanumeric number validation
- Business/Company VAT/TIN no:* - 11 digit validation
- Business/Company CST NO:* - 11 digit validation
- Business/Company Address (as mentioned on business license)* - 
	Address text in Multiline textbox*
	Country - dropdown*
	State - Dropdownn*
	City - dropdown*, Pin - Textbox*
	Alternate mobile number - Country code box (+ sign on left) and another box with 10 digit validation
	--Add another address  (fields as above)

**Other fields will be provided once finalized**
starred are compulsory fields

In terms of UI (like steps tabs)
Register button next to login.
On clicking, 
normal registration form filling>>validation>> option to continue as Free user or Upgrade to Bulk Buyer with features & pricing (details will be provided) mentioned below it.
if "Continue as free user" complete registration
else upgrade form

**Comment by ghost** [comment]
Facebook & Google+
Social login feature option to be implemented. Link account to social sites
Integrate with Socializer plugin

**Comment by negati-ve** [comment]
Closing this issue in view of updated information in issues #21 #22
