### ISSUE TITLE
plugin cleanup

### ISSUE THREAD

**Issue by negati-ve** [vivepandit24/visario#12]

**Comment by negati-ve** [comment]
Plugins to clean up
- [ ] string locator plugin  
This is useful for developers. Let's move this to wiki

**Comment by ghost** [comment]
# Required Plugins
 (tick when configured and ready for production)
- [ ] Ajax Search for WooCommerce
- [ ] Image Widget
- [ ] Shipping Manager for WooCommerce
- [ ] Super Socializer
- [ ] Tawk.to Live Chat
- [ ] VG WooCarousel
- [ ] WC Cancel Order
- [ ] WC Multiple Email Recipients
- [ ] Widgets in Menu for WordPress
- [ ] Woo Store Vacation
- [ ] Woocommerce Checkout Terms Conditions Popup
- [ ] WooCommerce Menu Cart
- [ ] WooCommerce PDF Invoices & Packing Slips
- [ ] WooCommerce Stock Manager
- [ ] WooCommerce Table Rate Shipping
- [ ] WooCommerce Waitlist
- [ ] WOOZOOm - Zooms On Details. Focuses on Sales
- [ ] WP All Import - WooCommerce Add-On Pro
- [ ] WP All Import Pro
- [ ] WP Security Audit Log

# Features required but not working as per needs
 (tick when configured and ready for production)
- [ ] AfterShip - WooCommerce Tracking
- [ ] Ajaxify filters
- [ ] WC Ajax Product Filter
- [ ] Woo Quick View
- [ ] Woocommerce Delivery Date
- [ ] WooCommerce Product Stock Alert

# Features Required and requires Check from my side
(tick when checked and confirmed)
- [ ] Multi Step Checkout For Woocommerce
- [ ] Giftable for WooCommerce
- [ ] One Click Order Re-Order
- [ ] Product Categories Designs for WooCommerce
- [ ] Recently viewed and most viewed products
- [ ] VG PostSlider
- [ ] Woo Already Bought
- [ ] Woocommerce Gift Wrapper
- [ ] WooCommerce Order Search
- [ ] WooCommerce Quick Buy
- [ ] WP Tao

# Plugins to buy
(tick when bought, configured and ready for production)
- [x] woocommerce collections wordpress plugin
- [x] woocommerce multiple customer addresses
- [x] table-rate shipping for woocommerce
- [x] tablerateshipping.com

# Not required
(tick when deleted)
- [x] Customer Specific Pricing (CSP) Lite for WooCommerce
- [x] Prices by User Role for WooCommerce (BASIC)
- [x] Page Builder by SiteOrigin
- [x] SiteOrigin Widgets Bundle
- [x] TI WooCommerce Wishlist
- [x] Ultimate Member
- [x] User Role Editor
- [x] Woo Custom Stock Status
- [x] Woo Message Support
- [x] WooCommerce - APG SMS Notifications
- [x] WooCommerce Cart Stock Reducer
- [x] WooCommerce Menu Extension
- [x] WooCommerce Role Based Price
- [x] WooCommerce Wholesale Prices
- [x] WOOF - WooCommerce Products Filter
- [x] WP Tao

**Rest plugins you guys can decide based on how its applied on website.**

**Comment by negati-ve** [comment]
tawk.to was deleted by me by mistake. 
Please reconfigure.

**Comment by ghost** [comment]
close it
