### ISSUE TITLE
top banner

### ISSUE THREAD

**Issue by negati-ve** [vivepandit24/visario#13]
please change the (wild) cat n bird image to something relevant . 
provide inputs on this

**Comment by ghost** [comment]
Need to display products details, offers and up comings. 
Still haven't formulated.

**Comment by negati-ve** [comment]
Let's move this forward and get a graphic done for this. 
This is a key element of the site and will possibly be the first impression for the users (or second, depending on how the landing pages are placed for SEO)

**Comment by vivepandit24** [comment]
Need images to finalize the banner image.

**Comment by negati-ve** [comment]
Please provide final images to finalize this.

**Comment by negati-ve** [comment]
create new issue if applicable

**Cleaning up**
