### ISSUE TITLE
Account-> Login redirects to wordpress login page

### ISSUE THREAD

**Issue by negati-ve** [vivepandit24/visario#15]
clicking on login:
![screen shot 2017-03-23 at 11 20 26 pm](https://cloud.githubusercontent.com/assets/13253073/24262202/669a9434-101f-11e7-97bb-25618e65c28d.png)

Takes the user to wordpress login :
![screen shot 2017-03-23 at 11 21 28 pm](https://cloud.githubusercontent.com/assets/13253073/24262309/a69ae96c-101f-11e7-936e-2daab63ce53d.png)

User should be taken to login/register/account page
![screen shot 2017-03-23 at 11 23 12 pm](https://cloud.githubusercontent.com/assets/13253073/24262803/3c5ec896-1021-11e7-9e78-23109d5ccb7a.png)

update link basically.

**Comment by vivepandit24** [comment]
Fixed and tested
