### ISSUE TITLE
FOOTER

### ISSUE THREAD

**Issue by negati-ve** [vivepandit24/visario#18]
![screen shot 2017-03-23 at 11 47 53 pm](https://cloud.githubusercontent.com/assets/13253073/24263445/3141e4d2-1023-11e7-8e7a-04f486e431c0.png)

input needed.

**Comment by ghost** [comment]
What kind of input required?

**Comment by negati-ve** [comment]
input regarding the final placement of information here.
- What information needs to be placed here
- in what order it needs to be placed
- how it should be aligned. (most users are accustomed to footer links and sometimes even scroll all the way down to find quick links they can't find elsewhere on the page. Just like everyone is accustomed to the fact that clicking on top logo gets you to home page. just an unsaid rule)

**Comment by ghost** [comment]
close it
