### ISSUE TITLE
Registration form [Wholesaler]

### ISSUE THREAD

**Issue by negati-ve** [vivepandit24/visario#21]
# Form fields
- [x] Business/Company name (as mentioned on business license)* - Textbox
- [x] Business/Company type - Radio button*
- [x] Sole Proprietorship
- [x] Partnership
- [x] Private Limited Company
- [x] Limited Liability Partnership (LLP)
- [x] Reason for purchase* - Multi Select
- [x] Personal Use
- [x] Re-sell
- [x] Business/Company Pan number - 10-digit alphanumeric number validation
- [x] Business/Company VAT/TIN no:* - 11 digit validation
- [x] Business/Company CST NO:* - 11 digit validation
- [x] Business/Company Address (as mentioned on business license)* -
- [x] Address text in Multiline textbox*
- [x] Country - dropdown*
- [x] State - Dropdownn*
- [x] City - dropdown*, Pin - Textbox*
- [x] Alternate mobile number - Country code box (+ sign on left) and another box with 10 digit validation
- [x] --Add another address (fields as above)

# Registration Flow
On basic registration form, user should be able to view two button,
- [x] "Continue as free user(Register)", see issue #22 
- [x] "Upgrade to Bulk Buyer"

- [x] On clicking "Upgrade to Bulk Buyer", User should be taken to a new form with form fields as seen above.

**Comment by negati-ve** [comment]
[ ] Facebook Social login feature option to be implemented.
[ ] Google+ Social login feature option to be implemented.

Integrate with Socializer plugin

**Comment by negati-ve** [comment]
- [x] Let's keep the text as "Upgrade to bulk buyer" instead of "be a wholeseller"?
![screen shot 2017-03-26 at 1 23 30 pm](https://cloud.githubusercontent.com/assets/13253073/24329546/8aabb9b6-1227-11e7-8195-5ca162b62a45.png)

Also,
option not available to user not logged in/Registered,
![screen shot 2017-03-26 at 1 23 38 pm](https://cloud.githubusercontent.com/assets/13253073/24329551/a606caf2-1227-11e7-985a-e75013e6d784.png)

- [ ] @vivepandit24: Please confirm with nishiyt and update this.

**Comment by negati-ve** [comment]
Tested. 
can confirm that submissions can be seen under admin-> form-> submissions-> wholeseller

**Comment by negati-ve** [comment]
@vivepandit24 
- [x] States are only for US 
![screen shot 2017-03-26 at 1 54 14 pm](https://cloud.githubusercontent.com/assets/13253073/24329724/8ad0c378-122c-11e7-8db7-0666fed2e4f1.png)

**Comment by negati-ve** [comment]
- [x] nishiyt, Please confirm the post submission message 
![screen shot 2017-03-26 at 1 54 43 pm](https://cloud.githubusercontent.com/assets/13253073/24329720/7098017e-122c-11e7-9292-0a98e67916a3.png)

**Comment by ghost** [comment]
- [x] Instead of term used "Wholeseller" or "Bulk buyer" use "Wholesale Buyer"
So
Upgrade to Wholesale Buyer
And highlight the link. Something prominent 
- [x] If user logged in put upgrade option above logout

- [x] Remove upgrade if not logged in in menu. 
- [x] Add Login / Register in place of Login

**Comment by ghost** [comment]
- [x] Add help text
- [x] As states not working other than indian ones
- [x] Add cities
- [x] Email field already taken. So remove from here
- [x] Reason for purchase - multi tick option and what is three (remove it)
- [x] Business / Company Address - multi line box
- [x] Add "Nearby Landmark" field after "Business / Company Address"
- [x] Address in the last - its a option for user to add multiple address. It depends on how multiple address plugin works
- [x] Shorten all the boxes as it is too elongated

**Comment by vivepandit24** [comment]
1. NEED the help text to be added and to which fields .(most are self explaintory).
2.  Country is drop down state and city is to be filled manually.
3.  Email Removed.
4.  Reason for purchase is multi select checkbox.
5.  All address are paragraphs and have a very large limit. If we have multi lines option the address on submission will break into the no of lines used.
6.  Nearby landmark field added.
7. Form width is shorter than before.

@nishiyt  please check and tick on the last comment as verification .

**Comment by ghost** [comment]
open a new issue with country state and pincodes thing as discussed with @vivepandit24 and close this issue
