### ISSUE TITLE
Registration form [BASIC USER]

### ISSUE THREAD

**Issue by negati-ve** [vivepandit24/visario#22]
# Form fields
- [x] Name*
- [x] Email (used for login) (verification)*
- [x] Password*
- [x] Mobile number (verification)* - Country code box (+ sign on left) and another box with 10 digit validation

# Registration Flow
It was previously discussed that the "Register button next to login."
- Keeping the new changes in mind, It is now a simpler implementation to have the login and registration option both on the same page as seen below
![screen shot 2017-03-26 at 11 50 24 am](https://cloud.githubusercontent.com/assets/13253073/24329130/6decc278-121a-11e7-97f4-3fb68618f3c8.png)

# Check when completed and tested.
- [x] option to continue as Free user [Register button]  
- [x] if "Continue as free user" complete registration
else upgrade form, see #21

**Comment by negati-ve** [comment]
- [x] Facebook Social login feature option to be implemented.
- [x] Google+ Social login feature option to be implemented.

Integrate with Socializer plugin

**Comment by negati-ve** [comment]
The registration fields don't need any plugins as of now for basic registration. I've extended woocommerce registration by code.

**Comment by negati-ve** [comment]
![screen shot 2017-03-27 at 12 02 33 am](https://cloud.githubusercontent.com/assets/13253073/24334041/b709f2ee-1280-11e7-8af6-561f910b9f82.png)

**Comment by negati-ve** [comment]
Assigned to @vivepandit24 for social login

**Comment by ghost** [comment]
- [x] Account created thank you email shows username
- [x] Add help text to each field
- [x] Email change to "Email (Used for Login)"
- [x] Country code box (+ sign on left)
- [x] Mobile verification set to next page or pull form down.
- [x] Once verified a page confirming account created and a highlighted prominent link as Continue as free user and Upgrade to a Wholesale buyer with a box below of benefits.
- [x] Remove Upgrade option
- [x] Mobile number & Email already registered should show before verifying with otp
- [x] Once validate mobile clicked resend otp should be disabled for 30 sec (or each try)
- [x] Make Validate and resend button small or match UI
- [x] Match Register button with login button

**Comment by vivepandit24** [comment]
Need to make a facebook app shall i do it on my personal account or is there a company account .

**Comment by vivepandit24** [comment]
And even google id for google signin

**Comment by vivepandit24** [comment]
![fb login visi](https://cloud.githubusercontent.com/assets/23717545/24530690/3d32e6b6-15d1-11e7-8ee7-148b310e5b9a.png)
Google signin is working fine .
Facebook  allows test login (screen shot attached)
socializer plugin is used here.

Wp social login is deactivated

**Comment by negati-ve** [comment]
From the list of changes

## Once validate mobile clicked resend otp should be disabled for 30 sec (or each try)
This feature is done on the backend. same session cannot resend otp within 30 secs. 
Also, even if user attempts to change the no post verification, backend ill only take original no as phone.

**Comment by negati-ve** [comment]
Closing this issue as this has gone stale and is no longer providing clear focus on any single issue. @nishiyt @vivepandit24
