### ISSUE TITLE
Custom menu links

### ISSUE THREAD

**Issue by negati-ve** [vivepandit24/visario#24]
![screen shot 2017-03-26 at 1 44 28 pm](https://cloud.githubusercontent.com/assets/13253073/24329642/77b7d97c-122a-11e7-9e48-4a8d440b226e.png)
When we move to another server (production) these links will need to be updated every time. (absolute links)

Instead use pages. (relative)

**Comment by vivepandit24** [comment]
some links are used which is not available in the menu pages .
Once changed custom links has to be changed

E.g

Wishlist,
Orders.

**Comment by vivepandit24** [comment]
I will revert to all the available menu pages and list the once that cannot be changed for future refrence.

**Comment by negati-ve** [comment]
yes, that'll be great ! 
make a list in this thread

**Comment by vivepandit24** [comment]
Image widget -  used for the logo 
Shop - page
profile name - to display the name of the user
Login / register - page
My Account - Custom link - to edit account detail.
My Order  - Custom link - to view orders
Wishlist - page
Upgrade to wholesale buyer - page
logout - user link
