### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by negati-ve** [vivepandit24/visario#3]
Needs more info. 

Is this the search Filter?
What exactly is not working here?

**Comment by vivepandit24** [comment]
In the shop the filter is only letting you select one option in each filter section .multiple choice is needed... e.g multiple categories  or multiple thickness.

**Comment by negati-ve** [comment]
This controlled by [Ajax_Product_Filter](https://visi.000webhostapp.com/wp-admin/admin.php?page=Ajax_Product_Filter)  ?

**Comment by negati-ve** [comment]
Ajax_Product_Filter  premium version is required for multi selection

**Comment by negati-ve** [comment]
This seems to be working (functionality wise)
![screen shot 2017-03-26 at 11 59 14 am](https://cloud.githubusercontent.com/assets/13253073/24329180/b4f2b424-121b-11e7-813d-95ed108df0b9.png)

# Tests 
- Checked 21swg or 0.81mm [results displayed correctly]
- Checked few other options [results displayed correctly]
- unChecked options  [results displayed correctly]
