### ISSUE TITLE
 Once verified a page confirming account created and a highlighted prominent link as Continue as free user and Upgrade to a Wholesale buyer with a box below of benefits.

### ISSUE THREAD

**Issue by negati-ve** [vivepandit24/visario#35]
I will take care of this.

**Comment by negati-ve** [comment]
Pointers to get this done. 

Create a new page with 
- Benefits of wholesale buyers 
in the same box/section,
- "Upgrade to wholesale buyer" button at the bottom and
- "Continue as free user" button along side the "Upgrade to wholesale buyer button"

Once this page is created,
insert this code to functions.php

```
function registration_redirect() {
    return home_url( '/wholesale-upgrade-page-post-registration' );
}

add_filter( 'registration_redirect', 'registration_redirect' ); 
```

**Comment by vivepandit24** [comment]
wholesale registration page
https://visi.000webhostapp.com/wholesale-benefits/

**Comment by ghost** [comment]
close it
