### ISSUE TITLE
 Country code box (+ sign on left)

### ISSUE THREAD

**Issue by negati-ve** [vivepandit24/visario#38]
@vivepandit24 please fix

**Comment by negati-ve** [comment]
close this today. comment here if help required.

**Comment by vivepandit24** [comment]
Please buy otp service first, this is dependent on OTP service provider

**Comment by negati-ve** [comment]
done. verified. waiting for confirmation to close issue.

**Comment by negati-ve** [comment]
this is done. 

**Cleaning up**
