### ISSUE TITLE
Manual adding/updating products in cart  based on communication with customer

### ISSUE THREAD

**Issue by ghost** [vivepandit24/visario#41]
Customer confused in finding product.
Describes requirement or issue via chat or messages
**Seller adds products based on the product discussed in the communication.
Further seller be able to add offers discount in the cart (for customer only left with making payment)**
Further buyer confirms the cart and makes payment

**Comment by negati-ve** [comment]
![screen shot 2017-08-19 at 10 43 47 pm](https://user-images.githubusercontent.com/13253073/29488805-ed96bcbc-852f-11e7-97c7-ef88319e1615.png)

Admins can switch to any user account and add products to cart. 

Please acknowledge and close this. My aim is to not keep any issue open more than 3 days.

**Comment by ghost** [comment]
after switching to other user from admin. Products gets added but does not show up on other user account

**Comment by ghost** [comment]
after switching user...it logs out of admin account. And to login back to admin requires logout from current switched user.

**Comment by ghost** [comment]
It works as there is a link below in the end to switch back.
