### ISSUE TITLE
Collection plugin

### ISSUE THREAD

**Issue by ghost** [vivepandit24/visario#44]
- [ ] Disable public collection
- [x] Disable "Add to Collection" for user who are not logged in
- [ ] In collection page add "Add to Cart" button to Products

**Comment by negati-ve** [comment]
"Disable public collection" by default the collections are private.. 
we shall remove the buttons to make a collection public.

**Comment by ghost** [comment]
Add to cart can be taken later...

**Comment by negati-ve** [comment]
limitations on collection plugin.

Issue is rotting. create new issue if applicable.

**Cleaning up**
