### ISSUE TITLE
Product input problem

### ISSUE THREAD

**Issue by ghost** [vivepandit24/visario#45]
- [x] Variation problem
- [x] Role based price not working not showing accurately
- [x] Attribute order changes after upload
- [x] Variation description completely incorrect output
- [x] images not showing up post upload

**Comment by negati-ve** [comment]
variation problem seems to be fixed, verify

**Comment by negati-ve** [comment]
attribute order is this correct? seems to be in order.. please confirm  

![screen shot 2017-07-18 at 8 46 42 pm](https://user-images.githubusercontent.com/13253073/28324977-58c20edc-6bfa-11e7-9967-0fcba5fbe1d5.png)

**Comment by negati-ve** [comment]
![screen shot 2017-07-18 at 8 45 06 pm](https://user-images.githubusercontent.com/13253073/28325013-6f43af6c-6bfa-11e7-8715-c78ed7dc295d.png)
![screen shot 2017-07-18 at 8 44 39 pm](https://user-images.githubusercontent.com/13253073/28325019-7417ff16-6bfa-11e7-87c8-eb0385ba2133.png)

![screen shot 2017-07-18 at 8 44 48 pm](https://user-images.githubusercontent.com/13253073/28325040-7fcdb3c8-6bfa-11e7-86b4-26e8321060eb.png)

description seems to match.. please clarify

**Comment by negati-ve** [comment]
images are showing up now

**Comment by negati-ve** [comment]
"Role based price not working not showing accurately"

Let's discuss this issue in detail over a screen share

**Comment by ghost** [comment]
For attribute order check the import setting and template....it shows the order perfectly....but after import it is not the same

**Comment by negati-ve** [comment]
Custom field added to fix attribute order. 
![screen shot 2017-07-18 at 8 46 42 pm](https://user-images.githubusercontent.com/13253073/28361694-39e358f2-6c97-11e7-9c09-5edf98f45824.png)

**Comment by negati-ve** [comment]
Custom field added to fix attribute order.
![screen shot 2017-07-19 at 3 30 10 pm](https://user-images.githubusercontent.com/13253073/28361731-5256a8c6-6c97-11e7-8852-234e8304ff10.png)

**Comment by negati-ve** [comment]
edits made and custom field added for role based pricing.. 
role based pricing is now functional.. 

Please test and verify.

```
wholesale test user:wholesale@test.com
wholesale test password:azL0H#iMX0Gbpz#6ktx8D)iV
```

**Comment by ghost** [comment]
Will test it with product input from start.

And for wholesale customer price range is not showing on top of attributes as shown for normal customer

**Comment by negati-ve** [comment]
done and verified for normal and wholesale user. 

Please do a clean product input and verify total product input.

**Comment by ghost** [comment]
Import issue with pvc solved but with normal copper pipe its having issues (earlier copper pipe worked perfectly)

**Comment by negati-ve** [comment]
Import template created by you has attribute values that don't exist in the uploaded csv/excel sheet.
![screen shot 2017-07-19 at 11 42 12 pm](https://user-images.githubusercontent.com/13253073/28382554-23025648-6cdc-11e7-8cdc-3a3381da58ff.png)

I have updated the values to match the sheet.
![screen shot 2017-07-19 at 11 42 35 pm](https://user-images.githubusercontent.com/13253073/28382590-4a2ba8f0-6cdc-11e7-9025-64f5aa90fe3b.png)


please verify

**Comment by ghost** [comment]
Input data comes up accurately
Check with copper fitting products....product page template is changed

**Comment by negati-ve** [comment]
In case of any template mismatch in the future all you have to do is goto product category and edit the product's category
![screen shot 2017-07-20 at 3 51 19 pm](https://user-images.githubusercontent.com/13253073/28412972-80f6ea0c-6d63-11e7-8b9e-17d654289131.png)

And change the template to "custom product template" by selecting from the "single product page" drop down as seen in the screenshot below: 
![screen shot 2017-07-20 at 3 51 59 pm](https://user-images.githubusercontent.com/13253073/28412988-8d0c38f6-6d63-11e7-85ff-0979dbdb1a82.png)

**Comment by negati-ve** [comment]
Shall I close this issue?

**Comment by ghost** [comment]
why not set it default for all?
That would be a better option rather than verifying after each and every upload and setting it right. Kind of an additional task
And products are gona have multiple categories.

**Comment by negati-ve** [comment]
This is a one time thing for new categories.

By default woo commerce comes with it's own template. if we over ride that and make our version default it will not be _upgrade proof._ 
Small updates to woo commerce or other plugins dependent on woo commerce may create trouble later on as they may not play well with our theme's structuring.
It's easy to go to the category page and edit the template. but if we change it and make this template default,
it'll be time consuming to figure out issues when templates break upon minor upgrades. 

https://docs.woocommerce.com/document/template-structure/, to achieve this, we will have to restructure our current theme completely. 
I don't recommend this as the outcome is very small compared to the issues it might bring about with future upgrades.

**Comment by ghost** [comment]
PVC attribute order again changed? eg PVC color comes as first attribute whereas it should be second last option.

**Comment by negati-ve** [comment]
create new issue if applicable to new setup
**cleaning up**
