### ISSUE TITLE
Tax not calculating on Product value

### ISSUE THREAD

**Issue by ghost** [vivepandit24/visario#47]
It calculates only on shipping and not on Product value
How to have multiple tax rates on single order?

**Comment by negati-ve** [comment]
please elaborate.. 
where do you expect the user to see tax added rates?
what tax rates are to be added to the base price?

**Comment by ghost** [comment]
check the cart with product...the total calculation does not add tax to product price.
And as per gst 
sale within state CGST and SGST both applies
Sale outside state IGST applies

**Comment by negati-ve** [comment]
Let's sit on this tonight post 9?

**Comment by ghost** [comment]
you can call now too

**Comment by negati-ve** [comment]
we shall reopen this if needed in future.. 
cleaning up
