### ISSUE TITLE
New account creation with verification while placing order

### ISSUE THREAD

**Issue by ghost** [vivepandit24/visario#48]
No verification setup is done. Please add

**Comment by negati-ve** [comment]
- [x] Sms gateway integration (msg91)
- [x] Sms verification (India)
- [x] Sms verification (worldwide)
- [x] Email verification
- [x] Auto logout on registration 
- [x] Wholesale benefits page (change text content as required from here: http://0ae.3e2.myftpupload.com/wp-admin/post.php?post=1143&action=edit)

**Comment by negati-ve** [comment]
Verified on WhatsApp. 
added notice on wholesale benefits page.

**Comment by ghost** [comment]
close it
