### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by ghost** [vivepandit24/visario#49]
Product image zoom and thumbnail
Product page not center aligned
Top bar menu alignment
Checkout tabs

**Comment by negati-ve** [comment]
product image zoom and thumbnail is available in new theme.
product page alignment is not an issue in new theme
top bar alignment is not an issue with new theme
checkout tabs done

**Comment by negati-ve** [comment]
create new issues if applicable to new theme. 
**Cleaning up**
