### ISSUE TITLE
New user order placing & registration

### ISSUE THREAD

**Issue by ghost** [vivepandit24/visario#50]
**Issue type 1**
After clicking Proceed to Checkout, it shows form to enter user details

User does not get to know the username
Mobile number not verified
Email not verified
Welcome message also not received
Password validation not done
Allows placing order without any verification

**Issue type 2**
Visit website and go to registration/login page...
fill details and user is allowed to place order without any verification
Further as Issue type 1

**Comment by negati-ve** [comment]
updated. 

checkout will redirect to registration if user is not registered. 
normal registration flow is followed and user can go back to check out then

**Comment by negati-ve** [comment]
to be done: 
email and phone MUST be verified before checkout .

**Comment by ghost** [comment]
Make one registration page everywhere.....add firstname lastname to it before going to Plans option

**Comment by negati-ve** [comment]
done. verifications pending

**Comment by negati-ve** [comment]
verified on WhatsApp group. closing this.

**Comment by ghost** [comment]
close it
