### ISSUE TITLE
Logout redirect page

### ISSUE THREAD

**Issue by ghost** [vivepandit24/visario#51]
After placing order and logout of the account order details still visible...see screenshot

![logout screenshot](https://user-images.githubusercontent.com/26554401/28268373-b6b17d96-6b1b-11e7-9367-d7863dab12a9.PNG)

**Comment by negati-ve** [comment]
done. now redirects back to homepage on logout.

**Comment by ghost** [comment]
above explained issue is solved...
But see new scenario below
User logs in 
adds product to cart
User logs out 
Still the product is seen in the cart and stays till checkout

Cart should get emptied

**Comment by ghost** [comment]
close it
