### ISSUE TITLE
Set email as only username

### ISSUE THREAD

**Issue by ghost** [vivepandit24/visario#52]

**Comment by negati-ve** [comment]
as in ? the username should be same as email address? but we are using only email for registration and login.

**Comment by ghost** [comment]
username as mentioned in the user details is also considered while login
eg try login with 
Username - r
pass - 12345678

you will be able to login

So just allow emails and no username

**Comment by negati-ve** [comment]
do we collect username at registration then?

**Comment by negati-ve** [comment]
As discussed, will set email as mode of registration and login.

**Comment by negati-ve** [comment]
Note:Admin logins will NOT be processed with usernames either. 
current login:pass (a:a) is now replaced with (industrialmetals@hotmail.com:a)

**Comment by negati-ve** [comment]
test email based logins.

**Comment by ghost** [comment]
email login works on website for users

For admin
Dashboard login still takes username...

**Comment by negati-ve** [comment]
overall transition to email based login will require core wordpress modification.
The modifications are done and in place but commented out.
Activating these changes will cause issues in the future if you upgrade wordpress of any other plugins dependent on core wordpress login code.

To avoid this, I've written new non-core wordpress code that will make sure users can login only with email, but admins can login with email and username.
Any upgrades to wordpress or woo commerce will not affect this code.

**Comment by ghost** [comment]
Makes sense...
Close the issue
