### ISSUE TITLE
Delivery to or pickup

### ISSUE THREAD

**Issue by negati-ve** [vivepandit24/visario#6]
Delivery to or pickup. If pickup option to select estimated date and time with notification as Product not picked up at specified time will incur storage charges on per day basis unless you notify the date and time change 36 hours prior the given date and time or scheduled time changed by us.

**Comment by vivepandit24** [comment]
Plugin is installed but need to check with more products and stock.

**Comment by ghost** [comment]
Plugin problem. Jumps to previous page and unable to select date.
UI also not up to the mark

@vivepandit24 if works with one product should work with all

**Comment by vivepandit24** [comment]
pickup becomes a part of the shipping process 
https://codecanyon.net/item/woocommerce-click-and-pick-local-pickup-/10530941

**Comment by negati-ve** [comment]
recoded the plugin to fit into multistep checkout.. 
please test

**Comment by negati-ve** [comment]
close this
