### ISSUE TITLE
When order exceeds stock (Backorder)

### ISSUE THREAD

**Issue by vivepandit24** [vivepandit24/visario#9]

**Comment by vivepandit24** [comment]
In the product page when the order is greater than the stock . Pop up to notify 
E.g 
30 in stock and you have 30 in your cart.

**Comment by vivepandit24** [comment]
In the checkout page ,after the order is added. Pop up to notify
E.g , for 300 units order.
Ready stock 30. Backordered 270.

**Comment by negati-ve** [comment]
possible duplicate #4

**Comment by negati-ve** [comment]
bump
